CREATE TABLE EXE_KPI_ER_OFFICEVISITS
   (	"ER_CPT_LEVEL" VARCHAR2(15 BYTE), 
	"CLM_LINE_LOB_CD" VARCHAR2(30 BYTE), 
	"CLM_PROD_BSNS_CAT_CD" VARCHAR2(30 BYTE), 
	"DRVD_CO_NM" VARCHAR2(100 BYTE), 
	"DRVD_LOB_CAT" VARCHAR2(10 BYTE), 
	"YR_MNTH_KEY" NUMBER, 
	"YR_MNTH_DT" DATE, 
        "CLM_LINE_PROC_CD" VARCHAR2(20 BYTE),
	"CAT_FLAG" VARCHAR2(20 BYTE), 
	"CLAIM_COUNT" NUMBER, 
	"DRVD_TOTAL_PAID_AMT" NUMBER,
    "ER_OFFICE_FLAG" VARCHAR2(20 BYTE)
   ) ;
