  CREATE TABLE "EXE_KPI_COVID_19" 
   (	"CLAIM_ID" VARCHAR2(1000 CHAR), 
	"CLCL_CL_SUB_TYPE" VARCHAR2(1000 CHAR), 
	"PLAN_CD" VARCHAR2(1000 CHAR), 
	"MEME_RECORD_NO" NUMBER(19,0), 
	"YR_DATE_KEY" NUMBER, 
	"YR_DATE_DT" DATE, 
	"CLAIM_COUNT" NUMBER, 
	"LOBD_ID" NUMBER(19,0), 
	"RUN_DATE" DATE, 
	"Final_Test_Rslt" VARCHAR2(1000 CHAR), 
	"DRVD_CO_NM" VARCHAR2(1000 CHAR), 
	"DRVD_LOB_CAT" VARCHAR2(1000 CHAR), 
	"Business_Cat_Desc" VARCHAR2(1000 CHAR)
   )